Google Colab, short for Google Colaboratory, is an online platform that provides a Python development environment in the cloud **[1]**. It allows you to write, execute, and collaborate on Python code directly in your web browser, without the need for any local installations or setup **[1]**. Below it one example of running a simple Python code to demostrate the Python Environment:

In [ ]:
print ('Hello World')

Hello World


The output should print the text "__Hello World__"

Colab integrates seamlessly with Jupyter Notebook, a popular interactive computing environment. It allows you to create and run code cells, view their output, and add text and visual elements using Markdown **[2]**. Below there are few more examples of Python code running through cells

In [ ]:
print(6)

6


In [ ]:
a = 5
b = 15
sum = a + b

In [ ]:
print(sum)

20


This notebook:

https://colab.research.google.com/drive/1viwPb5CMlAkKkZiIyrFUR_PSpSz1eeMP?usp=sharing 

covers the fundamentals of the Python programming language. This should bring a solid understanding of working with variables and solving expressions using various mathematical operations.

## Practise

In [ ]:
import time #importing libraries 

In [ ]:
print(time.ctime()) #printing function, used to display output text/data

Sun Mar 19 18:52:32 2023


In [ ]:
23*43 #multiplication

989

In [ ]:
a=7 #store value

In [ ]:
49/a #division

7.0

In [ ]:
a=2 
b=3
sum = a + b
sum

5

Python list/directories

In [ ]:
list1=['apple','banana','cherry']
list2=[1,5,7,9,3]
list3=[True, False, False]


In [ ]:
print ('This is list 1: ',list1)
print ('This is list 2: ',list2)
print ('This is list 3: ',list3)


This is list 1:  ['apple', 'banana', 'cherry']
This is list 2:  [1, 5, 7, 9, 3]
This is list 3:  [True, False, False]


In [ ]:
List_A = [1, 2, 3, 4, 5]
List_B = [11, 12, 13, 14, 15]

In [ ]:
print (List_A * List_B)


TypeError: ignored

TypeError: can’t multiply sequence by non-int of type ‘list’. 

## Exercise 1: **Introduction to Numpy**

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the PyData ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks **[3]**. Plus, we will use it to generate data for our Artificial Intelligence and Machine Learning applications later on!
NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays. 
Let's begin our introduction by exploring how to create NumPy arrays.
Before jumping into NumPy, first discuss Python list. 


* **Python list:**

Lists are used to store multiple items in a single variable.
> Collection of values

> Hold different types of data (String, Integers and Boolean data type)

> Add, remove or change elements


In [ ]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]

In [ ]:
print(list1)
print(list2)
print(list3)

['apple', 'banana', 'cherry']
[1, 5, 7, 9, 3]
[True, False, False]


* **Limitation of Python list:**

In [ ]:
List_A = [1, 2, 3, 4, 5]
List_B = [11, 12, 13, 14, 15]

In [ ]:
print(List_A * List_B)

TypeError: ignored

*Result: TypeError: can't multiply sequence by non-int of type 'list'*

In Python, it is not possible to multiply two lists together using the multiplication operator (*). The operator is not defined for list multiplication. List multiplication is typically used for list repetition or concatenation, not for element-wise multiplication. When two lists are multiplied, a TypeError is raised, indicating that a sequence (list) cannot be multiplied by a non-integer type (another list).

Python has no idea how to perform calculation with the list. So, in order to overcome this error, we have to multiply each element of list A with list B. 


In [ ]:
print( List_A[0] * List_B[0])

11


* **NumPy:**

Using the NumPy package provides a more efficient and concise approach to achieve accurate results. Unlike regular Python lists, NumPy arrays offer enhanced data analysis capabilities.

> NumPy serves as an alternative to regular Python lists.

> Utilizing NumPy allows for more efficient data analysis compared to using lists.

> It enables performing calculations over the entire array.

> Arrays in NumPy can have one or more dimensions.

To use the NumPy package, begin by importing it into your code:

In [ ]:
import numpy as np

Now let's create new two lists:

In [ ]:
List_A = [1, 2, 3, 4, 5] 
List_B = [11, 12, 13, 14, 15]

Let's convert list A and B into numPy array: 

In [ ]:
A = np.array(List_A)
B = np.array(List_B)

Now let's perfume different print statements:

In [ ]:
print (A)
print (B)

[1 2 3 4 5]
[11 12 13 14 15]


> Printing array A: This displays the contents of array A, which are the elements [1, 2, 3, 4, 5].

> Printing array B: This displays the contents of array B, which are the elements [11, 12, 13, 14, 15].






In [ ]:
print (A * B) #multiplying index by index index 0: 11 * 1 index 1: 2 *12 and so on

[11 24 39 56 75]




> Printing the element-wise multiplication of arrays A and B (A * B): This multiplies each corresponding element in A with the corresponding element in B, resulting in the array [11, 24, 39, 56, 75].



In [ ]:
print (A *2)

[ 2  4  6  8 10]




> Printing the scalar multiplication of array A by 2 (A * 2): This multiplies each element in A by 2, resulting in the array [2, 4, 6, 8, 10].



In [ ]:
print (A *2)

[ 2  4  6  8 10]




> Printing the scalar multiplication of array A by 2 (A * 2) again: This is a repetition of the previous statement, resulting in the same array [2, 4, 6, 8, 10].



In [ ]:
print (A + A)

[ 2  4  6  8 10]




> Printing the element-wise addition of arrays A and A (A + A): This adds each corresponding element in A with the corresponding element in A, resulting in the array [2, 4, 6, 8, 10].



In [ ]:
print (A + B)

[12 14 16 18 20]




> Printing the element-wise addition of arrays A and B (A + B): This adds each corresponding element in A with the corresponding element in B, resulting in the array [12, 14, 16, 18, 20].



* **Nested list (`array` function->NumPy):**

A nested list in Python is a list that contains other lists as its elements, forming a hierarchical structure. In other words, it is a list that can hold any type of object, including other lists (sublists), which can also contain their own sublists, and this nesting can continue to any level **[4]**.

Nested lists allow for the creation of more complex data structures, enabling the representation of multi-dimensional data or hierarchical relationships **[4]**. Each level of nesting represents a new dimension or level of hierarchy within the data structure.

Here's an example of a nested list:

In [ ]:
NL = [[1,2], [3,4], [5,6], [7,8],[9,10]]

In [ ]:
print(NL)

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]


Now let's try it using NumPy:

In [ ]:
NL1 = np.array(NL)
NL1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
print (NL1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


It can be noticed that NumPy keeps the shape of the nested list. 

*Practise exercise: Create a NumPy array with name `my_array` with the below elements*

In [ ]:
array = [ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ]
print(array) 

[[1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16]]


In [ ]:
my_array = np.array(array)
print(my_array)

[[ 1  4  5  6]
 [ 7  8  9 10]
 [11 12 14 16]]


* **Arrange function->NumPy:**

The NumPy `arange` function generates a 1-dimensional array with evenly spaced values within a specified interval **[5]**. It takes parameters such as the start and stop values, and an optional step value to determine the spacing between consecutive values **[5]**. The resulting array does not include the stop value. `arange` is commonly used in numerical computations and data analysis tasks **[5]**.

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

This will generate an array with evenly spaced number starting 0 up to 5 - not including 5.

In [ ]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

It can be included a step size in np.arange function. Let's introduce 2 as a step size.

In [ ]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

* **Zeros and Ones functions->NumPy:**

In NumPy, you can generate arrays filled with zeros or ones of specific dimensions using the `zeros()` and `ones()` functions, respectively. The `zeros()` function creates an array filled with zeros **[6]**, while the `ones()` function creates an array filled with ones **[7]**. By specifying the number of rows and columns, you can generate arrays with the desired dimensions **[6],[7]**.

In [ ]:
np.zeros(1)

array([0.])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Notice that Numpy gives zeros as `0.` as this indicates that these numbers are floating numbers.

Let's now create an 4x4 matrix of zeros.


In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

It can also be generated as a 4x15 matrix.

In [ ]:
np.zeros((4,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

If the numbers in the arrays are desired to be integers, the `dtype` (data type) needs to be specified as `int`.

In [ ]:
np.zeros((4,15), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Similarly, it can be done with ones.

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

* **Linspace function->NumPy:**

Linspace is a function in NumPy that generates an array of evenly spaced numbers within a specified interval **[8]**. It takes a start and end value, along with the number of elements desired in the sequence, and creates an array with evenly distributed values between the start and end points **[8]**.

In [ ]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

The number of evenly spaced numbers can be increased to create a more dense array. An array of 20 evenly spaced numbers between 0 and 20 can be created.

In [ ]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

* **Eye function->NumPy:**

An identity matrix, also known as an "eye" matrix, is a special square matrix in which all the elements along the main diagonal are 1, and all other elements are 0. It serves as the identity element in matrix multiplication, meaning that when multiplied with any other matrix, it does not change the matrix **[9]**. In NumPy, the `eye()` function is used to create identity matrices.

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

Creating identity matrix is very useful for many linear programming and algebra applications. 

* **Random sampling functions->NumPy (rand):**

Random sampling `numpy.random` is a module in the NumPy library that allows for generating random numbers and arrays **[10]**. It offers functions like `random`, `randint`, `normal`, and `choice` to generate random values based on different distributions and requirements **[10]**. These functions are commonly used for simulations, statistics, and machine learning tasks. The generated random numbers are pseudo-random and can be controlled using a seed value **[10]**. In short, the function `numpy.random.rand()` creates an array with a specified shape and fills it with random values sampled from a uniform distribution over the interval (0, 1).

In [ ]:
np.random.rand(3)

array([0.78897674, 0.65362383, 0.72216022])

In [ ]:
np.random.rand(2)

array([0.57065923, 0.54215405])

In [ ]:
np.random.rand(2,3)

array([[0.43336248, 0.43775801, 0.67185037],
       [0.23930387, 0.94214959, 0.87163831]])

Two random numbers with a uniform distribution between zero and one can be obtained. If the cell is run again, different random numbers will be generated.

* **Random sampling functions->NumPy (randint):**

The `numpy.random.randint` function returns a random array of integers within the specified range and shape **[10]**. This function is useful for generating random integer values for various applications, such as simulations, random sampling, or generating test data **[10]**.

In [ ]:
np.random.randint(0,100)

97

In [ ]:
np.random.randint(0,200,15)

array([134,  21, 110,  88, 145,  75,  10, 199,  41,  56, 154, 110,  49,
       159, 104])

In [ ]:
np.random.randint(0,200,(3,5))

array([[ 81, 170,  31,  14,  31],
       [ 58, 108, 195, 161, 101],
       [  3,  28,  65,  98, 153]])

* **Reshape function->NumPy:**

Reshaping in NumPy refers to changing the shape of an array without modifying the data. It involves creating a new array with a different arrangement of elements **[11]**. The `reshape()` function in NumPy is used for this purpose. It takes the desired shape as input and returns a new array with the same data but in the specified shape **[11]**. Reshaping is useful for tasks like dimension conversion and preparing data for analysis or visualization **[11]**.

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

By using the `reshape()` function, we can reshape the `arr` array into a 5x5 array. Importantly, this operation does not modify the original `arr` array. Even if the `reshape()` function is called multiple times, the original `arr` array remains unchanged.

* **Max, Min, Argmax, Argmin functions->NumPy:**

> max: A NumPy function that returns the maximum value in an array.

> min: A NumPy function that returns the minimum value in an array.

> argmax: A NumPy function that returns the index of the maximum value in an array.

> argmin: A NumPy function that returns the index of the minimum value in an array.

These functions are useful for finding the maximum or minimum values in an array, as well as determining their index positions. They provide efficient ways to analyze and manipulate numerical data using NumPy arrays **[4]**.

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.max()

24

In [ ]:
arr.min()

0

In [ ]:
arr.argmax()

24

In [ ]:
arr.argmin()

0

* **Dtype function->NumPy:**

In NumPy, "dtype" refers to the data type of elements in a NumPy array. It represents the specific type of values stored, such as integers or floats. By accessing the "dtype" attribute, you can determine the data type of the array's elements, allowing for proper data handling and type-specific operations.

In [ ]:
arr.dtype

dtype('int64')

## Refrences

**[1]** “Google colaboratory introduction,” Google Colaboratory Introduction - AguaClara Tutorial v0.1.0 documentation. Available at: https://aguaclara.github.io/aguaclara_tutorial/colab/colab-introduction.html (Accessed: March 20, 2023). 

**[2]** "Google colaboratory markdown", Google Colab. Available at: https://colab.research.google.com/notebooks/markdown_guide.ipynb (Accessed: March 20, 2023).

**[3]** “NumPy documentation,” NumPy documentation - NumPy Manual. Available at: https://numpy.org/doc/stable/ (Accessed March 20, 2023).

**[4]** Y. Tang, “Nested lists in Python,” PythonAlgos. Available at: https://pythonalgos.com/nested-lists-in-python/ (Accessed March 20, 2023). 

**[5]** “Numpy.arange,” numpy.arange - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/generated/numpy.arange.html (Accessed March 20, 2023). 

**[6]** “Numpy.zeros,” numpy.zeros - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/generated/numpy.zeros.html (Accessed March 20, 2023). 

**[7]** “Numpy.ones,” numpy.ones - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/generated/numpy.ones.html (Accessed March 20, 2023). 

**[8]** “Numpy.linspace,” numpy.linspace - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/generated/numpy.linspace.html (Accessed March 20, 2023). 

**[9]** “Numpy.eye,” numpy.eye - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/generated/numpy.eye.html (Accessed March 20, 2023). 

**[10]** “Random sampling (numpy.random),” Random sampling (numpy.random) - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/random/index.html (Accessed March 20, 2023). 

**[11]** “Numpy.arange,” numpy.arange - NumPy Manual. Available at: https://numpy.org/doc/stable/reference/generated/numpy.arange.html (Accessed March 20, 2023). 